version: '2.2'
services:
  mrjeff:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mrjeff
    ports:
      - 8080
    networks:
      - network1

networks:
  network1: